metadata:
  #  Must match the 'spring.application.name' property of the application
  name: ${project.artifactId}
data:
  application.properties: |
    # spring application properties file
    greeting.backendServiceHost=backend
    greeting.backendServicePort=80